### ISSUE TITLE
The detection doesn't work for me

### ISSUE THREAD

**Issue by rekire** [Sor3nt/Amazon-Fire-TV-Stream#4] opened 2018-07-11 19:17 UTC
I'm checking your code. It crashes for me since you use in [line 65](https://github.com/Sor3nt/Amazon-Fire-TV-Stream/blob/master/FireTvDns.js#L65) the value 1 which cannot be converted to upper case. When I use instead the value 'IN' which will be resolved to 1 it does not return any data.

Any idea how I can make you code working? Btw please add your package.json so that we can know the versions you are using.

**Comment by Sor3nt** [comment] 2018-07-11 19:27
yea your right , the dns handler changed. The value "IN" is correct and works very well, i just change 1 to "IN" and start the index.js

[FireTvDns] Listening on  0.0.0.0
[FireTvDns] Build Broadcast payload for _amzn-wplay
[FireTvDns] Send payload:  <Buffer 00 00 00 00 00 01 00 00 00 00 00 00 0b 5f 61 6d 7a 6e 2d 77 70 6c 61 79 04 5f 74 63 70 05 6c 6f 63 61 6c 00 00 21 80 01>
[FireTvDns] Payload submitted
Found Device  { target: '192-168-0-13.local', port: 50717 }

About the "old" package.json, i am so sorry i dont have this anymore :/

**Comment by Sor3nt** [comment] 2018-07-11 19:28
are your sure that the FireTv are in the same network ?

**Comment by Sor3nt** [comment] 2018-07-11 19:31
patch + (new) json is commited

**Comment by rekire** [comment] 2018-07-11 19:46
Wow you are quick. Yeah, the FireTV is in the same network. I am also able to see my FireTV in the FireTV App in an Android App called "Service Browser".

**Comment by Sor3nt** [comment] 2018-07-12 04:50
Hmm. Are you on Mac ? Can you try to Call "dns-sd -B _amzn-wplay._tcp local"
And then send me please the Output.

**Comment by Sor3nt** [comment] 2018-07-12 04:56
Please also try to run the Tool at least for 5 Minutens. The firetv Is silence when many DNS are requested

**Comment by rekire** [comment] 2018-07-12 05:17
I'm using Windows for development, later it should run on Linux. I'll check asap if that command works on the windows bash too.

I canceled the execution after at most 5 request. I'll try to run it much longer

**Comment by Sor3nt** [comment] 2018-07-12 05:29
I am not a windows man, last windows was Windows 95 ^^
But i would guess windows has maybe some firewall features per default active that blocks your requests.

Try with dns-sd or any other dns service lookup tool if you can reach the firetv from your windows.

**Comment by rekire** [comment] 2018-07-12 18:26
That is still strange. I installed the bonjour sdk from Apple just to have the dns-sd command. And I got no results. However on my linux box it seems to work fine.

I found on https://www.ctrl.blog/entry/windows-mdns-dnssd that there are some limitations on mdns on Windows 10:

>All DNS‐SD APIs and functionality is entirely disabled if you’re running a machine with a Hyper‐V kernel and route traffic through a Network Virtualized Switch. The other network discovery protocols deployed by Windows NBNS, LLMNR, and SSDP all still work even though DNS‐SD is made unavailable. A very peculiar limitation, however, the Settings app: Network: Ethernet is also entirely broken in this scenario, so the newer Windows APIs may not entirely understand a switched interface from a virtualization host’s perspective.

I cannot remember exactly, but it is very likely that I have enabled Hyper-V from some older testing.

**Comment by Sor3nt** [comment] 2018-07-13 05:23
Oh ok but nice to hear that it works on your linux 👍 
So the problem is OS related, i close the issue and thanks for the contribution

**Closed as completed by Sor3nt** 2018-07-13 05:23 UTC
